artifact_location: /content/gdrive/My Drive/rl_class/week-1-intro-to-deep-rl-and-agent-training-environments-onenoc/submission/mlflow/149248889571836481
creation_time: 1694656318686
experiment_id: '149248889571836481'
last_update_time: 1694656318686
lifecycle_stage: active
name: my_experiment
